- hosts: all
  tasks:
  - name: check java version
    shell: java -version 2>&1| grep version|awk '{print $3}'|sed 's/"//g'
    register: java_version
    ignore_errors: True
  - name: print java_version
    debug:
      msg: "{{ java_version }}"
  - name: Intall if java not installed
    yum:
      name: java-1.8.0-openjdk
      state: present
    when:
    - ansible_facts['os_family'] == "RedHat"
    - java_version.stdout == ""
